### ISSUE TITLE
模型的执行顺序?

### ISSUE THREAD

**Issue by lin171110** [PeiJieSun/diffnet#1]
您好!
请问项目执行的顺序是什么样的呢?运行entry.py总是提示NameError: name 'diffnet' is not defined

**Comment by PeiJieSun** [comment]
你好，我只在linux环境下测试通过，如果是windows环境的话，我不是很清楚。一般只需要把项目克隆到本地电脑上，然后进入目录diffnet，执行python entry.py --xxx 就可以正常执行了。

**Comment by lin171110** [comment]
那么entry.py只是显示运行的参数吧？实验结果在train里面吗


------------------ 原始邮件 ------------------
发件人: "PeijieSun"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午11:28
收件人: "PeiJieSun/diffnet"<diffnet@noreply.github.com>;
抄送: "流恋月影"<2287802202@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [PeiJieSun/diffnet] 模型的执行顺序? (#1)




你好，我只在linux环境下测试通过，如果是windows环境的话，我不是很清楚。一般只需要把项目克隆到本地电脑上，然后进入目录diffnet，执行python entry.py --xxx 就可以正常执行了。

**Comment by PeiJieSun** [comment]
为了简化code，我把模型的临时参数保存的code删掉了，训练日志会记录在log目录下。

**Comment by PeiJieSun** [comment]
> 那么entry.py只是显示运行的参数吧？实验结果在train里面吗
> […](#)

log_path = os.path.join(os.getcwd(), 'log/%s_%s.log' % (conf.data_name, conf.model_name)) 在train.py第22行

**Comment by lin171110** [comment]
好的，我再看看，谢谢------------------ 原始邮件 ------------------
发件人: "PeijieSun"<notifications@github.com>
发送时间: 2019年5月8日(星期三) 中午11:37
收件人: "PeiJieSun/diffnet"<diffnet@noreply.github.com>;
抄送: "lin171110"<2287802202@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PeiJieSun/diffnet] 模型的执行顺序? (#1)


 
那么entry.py只是显示运行的参数吧？实验结果在train里面吗
 …
  
log_path = os.path.join(os.getcwd(), 'log/%s_%s.log' % (conf.data_name, conf.model_name)) 在train.py第22行
 
&mdash;
