### ISSUE TITLE
about pretain

### ISSUE THREAD

**Issue by ZainZhao** [PeiJieSun/diffnet#10]
你好，请问我执行您readme中的代码提示找不到
![image](https://user-images.githubusercontent.com/28838928/77427684-c3669200-6e11-11ea-8ed4-d552e588548c.png)
但是我已经下载了link中的pretain并解压，里面只有三个文件，都是上面那串字符再加后缀的，没有单独的这个文件
![TIM截图20200324205715](https://user-images.githubusercontent.com/28838928/77427846-12142c00-6e12-11ea-82bc-5f8e755235a3.png)
不知这是什么问题呢？非常感谢

**Comment by PeiJieSun** [comment]
你好，这个是tensorflow保存模型默认的格式，执行是没有问题的。

**Comment by ZainZhao** [comment]
非常感谢大佬，是我的中文路径有问题（尴尬）
