### ISSUE TITLE
Have your group opened the source code of DiffNet++?

### ISSUE THREAD

**Issue by johnny161** [PeiJieSun/diffnet#11]
谢谢您的工作，我有两个问题如下：
1.请问你们有开源DiffNet++的代码嘛？
2.Flicker的数据集需要怎么获取和处理呢？

**Comment by PeiJieSun** [comment]
1. 不好意思，DiffNet++尚在审稿阶段，我们打算等论文接受了会把代码公布出来
2. Flickr的数据集请见https://drive.google.com/open?id=1h3xGUOxhWs0MenmLJ_ajHuqB4mrLHT3U
