### ISSUE TITLE
convertDistribution中的一些疑问

### ISSUE THREAD

**Issue by lcy19991113** [PeiJieSun/diffnet#12]
请问一下作者 ，diffnet.py的第48行y = (x - mean) * 0.2 / tf.sqrt(var)，这里的0.2是什么含义呀？

**Comment by PeiJieSun** [comment]
y = (x - mean) * 0.2 / tf.sqrt(var) 这句话的意思是改变x的分布为均值为0，标准差为0.2的分布。

**Comment by lcy19991113** [comment]
> y = (x - mean) * 0.2 / tf.sqrt(var) 这句话的意思是改变x的分布为均值为0，标准差为0.2的分布。
谢谢！还有就是请问一下这里的标准差选择0.2而不选择1是有什么好处嘛

**Comment by PeiJieSun** [comment]
这个分布尽量选方差小一些比较好，太大了的话，分布中的数值比较大，导致得到的用户和产品的表征也比较大，计算的评分比较高，不利于优化之类的。当然，你可以自己尝试一下。因为这个数值可以修改看看结果如何。

**Comment by lcy19991113** [comment]
非常感谢您的回答！！
