### ISSUE TITLE
About Yelp Dataset

### ISSUE THREAD

**Issue by Archerxzs** [PeiJieSun/diffnet#18]
Hello! Can you provide the code for processing the Yelp dataset? I want to know the relationship between the id in the data set you provided and the original data set.
I really appreciate your help

**Comment by PeiJieSun** [comment]
Sorry, we have no code for processing the Yelp dataset kept.

**Comment by PeiJieSun** [comment]
I think you can process the dataset by yourself. And you just need to keep the user-item interaction records and user-user social links.
