### ISSUE TITLE
Understanding of num_evaluate?

### ISSUE THREAD

**Issue by 0oshowero0** [PeiJieSun/diffnet#2]
Hi, I feel confused about the _num_evaluate_ in config file. Does this parameter controls how many samples are used during evaluate process, no matter how many examples in the dataset file **yelp.test.rating**?

Another question: It seems that the code can not fully use the power of GPU when the dataset is really large. In my case, I found the GPU utilization is 0 during some time in training although the GPU memory is full. And the code can only use 1 CPU core, which is also a pity.

**Comment by PeiJieSun** [comment]
Thanks for your attention. Following are the answers to the questions.
1. The num_evaluate is used to control the number of negative samples when testing the model. If there are N samples in test data, we will sample num_evaluate * N unobserved user-item pairs as the negative samples.
2. This code just can utilize one GPU core, it's not easy to extend this code to multiple GPUs, but if you are interested in, you are welcome to modify this code.
