### ISSUE TITLE
Pretraining details

### ISSUE THREAD

**Issue by YH-UtMSB** [PeiJieSun/diffnet#20]
Hi Peijie, thank you for open sourcing the models. I am trying to re-implement diffnet in pytorch and it would be a great help if you could let me know the details of model pretraining. Specifically, how was the model by the name "diffnet_hr_0.3437_ndcg_0.2092_epoch_98.ckpt" trained? Thanks in advance.

**Comment by PeiJieSun** [comment]
The only thing you need is to run the code without any pre-training model, saving the model when the model achieves the largest NDCG value.

**Comment by PeiJieSun** [comment]
And you can refer to the paddlepaddle version of our model at this link https://gitee.com/peijie_hfut/diffnet-paddlepaddle. The paddlepaddle is similar to the pytorch.

**Comment by YH-UtMSB** [comment]
Thanks for the reply! This is very helpful.
