### ISSUE TITLE
How do you set the parameter for SVD++?

### ISSUE THREAD

**Issue by ll0ruc** [PeiJieSun/diffnet#22]
Hi, when I run SVD++ on [yelp](https://drive.google.com/drive/folders/1hIkRDIVI87CUM4xFGjHMeipOlPz97ThX), ` self.final_user_embedding = self.user_embedding + user_embedding_from_consumed_items`, while during 300 epochs, the best performance just achieve hr: 0.1282, ndcg:0.0770,

**Comment by PeiJieSun** [comment]
Sorry, I forgot the details.  I suggest you can try to implement the BPR model first. Then you can add the explicit and implicit neighbors of the users to the user embedding in the BPR model.

**Comment by ll0ruc** [comment]
> Sorry, I forgot the details. I suggest you can try to implement the BPR model first. Then you can add the explicit and implicit neighbors of the users to the user embedding in the BPR model.

I have implement BPR on yelp, and it performs on par with the paper. While using SVD++ in ranking task, I have some confuse. The SVD++ is 
![image](https://user-images.githubusercontent.com/34205771/164132181-36aa7fb7-09f0-4495-becd-569942966a46.png)
It covers rating task, i, j is the user and item, the u is the mean rating, bi, bj is the bias. mij is the explicit rating, the I(i) and the ys refer the implicit information. So when adapting it to a ranking task just with implicit information,
![image](https://user-images.githubusercontent.com/34205771/164133435-3dc56428-4c1b-44b6-a62c-653535c0e0fb.png)
 I do not know whether the understanding is right or not? Hope you give some clarification. Thank you

**Comment by PeiJieSun** [comment]
The original SVD++ is designed for the rating prediction task, and its objective function is based on the MSE loss. As our task is the ranking task, we optimize model by utilizing the pair-wise loss. To compare the SVD++ and our proposed model fairly, **we should also optimize the SVD++ model with the pair-wise loss**. Comparing with the BPR model, the key component of the SVD++ model is enriching the user embedding with the users' neighbors information, such as explicit consumed item neighbors, or implicit user neighbors. With the help of the users' explicit and implicit neighbors, the SVD++ model should outperform the BPR model. If you have reproduced the BPR model, the next thing you can do is modifying the user embedding part of the BPR model, i.e., finding the explicit and implicit neighbors of the target user, and treating the summed neighbors' embeddings and the target user's embedding as the target user's new embedding. Then, you can optimize the 'new'-BPR model directly. The 'new'-BPR model equals the SVD++ model.

**Comment by ll0ruc** [comment]
The BPR for ranking task is 
![image](https://user-images.githubusercontent.com/34205771/164173742-fb4b6eae-5b67-467a-a2db-4f4d0ebdb2ca.png)
According to your description, a 'new'-BPR means that 
![image](https://user-images.githubusercontent.com/34205771/164174416-680d8905-ff71-45e8-b555-e02b301994a7.png)
There are only implicit neighbors of the user here, means items who consumed by user u. So in the adding for new user's embedding, summed the implicit neighbors embedding q. While in the SVD++  for rating prediction, the implicit neighbors embedding is not q, another embedding y, so I am not sure the implicit neighbors embedding use q (the same to the item embedding) or user a new y (size is same to q)?

**Comment by PeiJieSun** [comment]
I think it doesn't matter, the final results can tell us which is better. And what we should do is selecting the better one. Or you can strictly according to the original SVD++ paper. By the way, the items which are consumed by the target user called explicit neighbors. And the neighbors who are similar to the target user called implicit neighbors, you can find these implicit neighbors with the Pearson(Cosine) Similarity measurement. You can use only the implicit interactions of two users, i.e., the proportion of common items are consumed by two users. In my opinion, only adding the explicit neighbors already boost the performance of the older BPR, and adding the implicit neighbors can further boost the performance of the recommendation model. 

Here is an example to calculate the similarity of two items according to their interaction history, you can also calculate the similarity of two users according to this same way.
line 73-80: https://github.com/openbenchmark/BARS/blob/master/candidate_matching/benchmarks/ItemCF/ItemKNN.py

**Comment by ll0ruc** [comment]
Until now, I already understand what you mean. Thank you very much for your corrections and explanations. In the end, I put my best wishes for you!

**Comment by PeiJieSun** [comment]
My pleasure.
