### ISSUE TITLE
社交扩散过程

### ISSUE THREAD

**Issue by lin171110** [PeiJieSun/diffnet#3]
您好!对于社交扩散过程不是很理解,
first_gcn_user_embedding=self.generateUserEmbeddingFromSocialNeighbors(self.fusion_user_embedding)
second_gcn_user_embedding=self.generateUserEmbeddingFromSocialNeighbors(first_gcn_user_embedding)
代码中这应该是两层所表示的扩散过程,但是不是可以这样理解每次都是前一层的输出乘以 社交关系矩阵呢,这样不弱化了社交关系影响了吗?

**Comment by PeiJieSun** [comment]
你好，代码可以理解为每次都是前一层的输出乘以社交关系矩阵，连续乘上两次社交关系矩阵，确实会让社交影响力变小，但是这里变小的影响力来自于邻居的邻居，我们称之为用户的二阶邻居。也就是说经过两次矩阵相乘操作，来自每个用户的二阶邻居的影响力会变小，但是用户的一阶邻居带来的影响力还是没有任何变化的。而且，用户的二阶邻居的影响力小于一阶邻居的影响力，在现实生活中是完全合情合理的。

**Comment by lin171110** [comment]
嗯嗯,可是最终扩散层输出的是每个用户的二阶邻居的影响力吧,那用户的一阶影响力在预测过程是如何起作用的呢?

**Comment by PeiJieSun** [comment]
相对于一个目标用户，第一次操作就已经将用户的一阶邻居的信息融合到每个节点中了，第二次操作是再次融合了目标用户的一阶邻居的信息，但是第二次融合的目标用户的一阶邻居的信息中包含了这名用户一阶邻居的一阶邻居的信息，所以第二次操作可以实现对目标用户二阶邻居信息的融合。并不是两次操作最终的输出只是目标用户的二阶邻居的信息，但是两次操作可以实现使用目标用户的一阶邻居作为桥梁，实现对用户二阶邻居信息的融合。

**Comment by lin171110** [comment]
嗯,明白了,非常感谢!

**Comment by PeiJieSun** [comment]
同时也谢谢你对我们工作的关注
