### ISSUE TITLE
请问user feature和item feature是必须的吗？

### ISSUE THREAD

**Issue by ZikaiGuo** [PeiJieSun/diffnet#5]
作者您好！

我想将diffnet用在一些不带user feature和item feature的数据集上。我将每个用户和物品的feature都改为长度很短的零向量（例如[0,0,0,0,0]）。按照论文里的公式，这样改动后user feature和item feature都不会起作用，而社交信息依然能起作用。但我做了这样以后会导致训练时train loss、val loss、test loss均为nan，模型无法正常训练。

请问我这样来去掉额外的feature信息是否可行？您是否试过把diffnet修改后用在不带user feature、item feature的数据集上？ 谢谢！

**Comment by PeiJieSun** [comment]
你好，这样子去掉额外的feature是不可行的，因为0的存在，使得模型在反向传播训练时，导致梯度出现nan值。

去掉额外的feature的方法是：
在diffnet.py文件中，
第98行，修改为：
`self.final_item_embedding = self.fusion_item_embedding = self.item_embedding`
第107行，修改为：
`self.fusion_user_embedding = self.user_embedding`

**Comment by ZikaiGuo** [comment]
太感谢了！谢谢您！
