### ISSUE TITLE
About the combination part

### ISSUE THREAD

**Issue by namenotexist** [PeiJieSun/diffnet#8]
![image](https://user-images.githubusercontent.com/40298904/63252450-65356780-c2a2-11e9-99cc-cf1c80c78b75.png)

**Comment by namenotexist** [comment]
this fomular seems not appeared in your code

**Comment by PeiJieSun** [comment]
In `diffnet.py` line 111, we simply this operation with `add` operation when we implement this model. But you can also modify the `add` operation to this one, maybe it will cost you some time to tune the parameters. Thank you for paying attention to our work.

**Comment by namenotexist** [comment]
Thanks replying. I think you must have been do some experiment comparing this two aggregation method, do you have some insight about the advantage and disadvantage about these two method

**Comment by PeiJieSun** [comment]
Yeah, I think the `add` operation is very easy to implement, and it can do help you keep all input information, but the `concatenate` operation seems not effective when keeping the input information, that's also the reason I select `add` operation in the experiment. But as you know, the written about the model should be interesting and sometimes complicated. But if you implement this model, I think `add` operation may be the better choice.
