### ISSUE TITLE
您好，我想我想问一下数据集中yelp的user_vector和 item_vector是怎么得到的，可否告知这些feature的含义以及生成方法？

### ISSUE THREAD

**Issue by zcjia** [PeiJieSun/diffnet#9]

**Comment by PeiJieSun** [comment]
你好，yelp中的user vector和item vector的来源可以分为以下几个步骤：
1. 使用gensim的word2vec工具包对yelp数据集中所有文本数据进行训练，得到一个word2vec模型参数。
2. 统计yelp数据集中所有评论数据，针对每条评论数据，该条评论数据都包含不定个数的单词，将这些单词的vector从wordvec中获取到，并取这些单词vector的均值作为该条评论数据的vector。
3. 统计yelp数据集中每个用户或者产品关联到的评论数据，根据步骤2获取每条评论数据的vector，并将用户/产品对应的所有评论数据的vector取均值，作为该用户/产品的vector。

**Comment by zcjia** [comment]
非常感谢。
